name: CI - Notely

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Use your Go version

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Run tests
      - name: Run Go tests
        run: go test -v ./...
