name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      # Step 3: Build the Go app
      - name: Build app
        run: ./scripts/buildprod.sh

      # Step 4: Log in to Docker Hub
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t abicons/notely:latest .

      # Step 6: Push Docker image
      - name: Push Docker image
        run: docker push abicons/notely:latest
